name: Type Check & Linting

env:
  CI: true

on:
  pull_request:

jobs:
  tsc_lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org/'

      - run: yarn --frozen-lockfile

      - run: yarn build:packages

      - run: yarn tsc

      - run: yarn lint
